### ISSUE TITLE
Replicate like Ping CRM

### ISSUE THREAD

**Issue by goldcoders** [xalunda/inertiajs-laravel-vuetify#3]
Hi I saw few things needs to be concern or not,
Login pages has no middleware a login user shoulnt see this anymore
Pagination not using serverside pagination like ping crm

**Comment by xalunda** [comment]
Hi there!

Login page correctly has `guest` middleware.
Should you go to /login while auth, you should be redirected to the dashboard. This works on fresh install on my end.

There is no server-side pagination example indeed. I needed a quick template using this stack, and I decided to share it with the community :)

Feel free to submit a PR if you feel like sharing more functionalities ;)

**Comment by goldcoders** [comment]
would like to make a pr ,of working serverside pagination i have a working version on my repo,..

**Comment by xalunda** [comment]
Sure go for it :)
Thanks for your contribution 🥇
